---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-cm
  labels:
{{ include "app.labels" . | indent 4 }}
data:
  REACT_APP_HOME_SERVER_URL: "https://synapse.{{- .Values.settings.hostname -}}"
---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: "{{ include "app.fullname" . }}-nginx-configs"
  labels:
{{ include "app.labels" . | indent 4 }}
data: {{ .Values.nginx.additionalConfigs | default "{}" }}
