{{/*
SPDX-FileCopyrightText: 2023 Nordeck IT & Consulting GmbH"
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if .Values.ingress.enabled -}}
---
apiVersion: "{{ include "common.capabilities.ingress.apiVersion" . }}"
kind: "Ingress"
metadata:
  name: "{{ include "common.names.fullname" . }}"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ coalesce .Values.ingress.host (printf "%s.%s" .Values.global.hosts.neoboard .Values.global.domain) | quote }}
      secretName: "{{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "common.labels.standard" . )) }}"
  {{- end }}
  rules:
    - host: {{ coalesce .Values.ingress.host (printf "%s.%s" .Values.global.hosts.neoboard .Values.global.domain) | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" $) "servicePort" 8080 "context" $) | nindent 14 }}
...
{{- end }}
