# SPDX-FileCopyrightText: 2023 Nordeck IT + Consulting GmbH"
# SPDX-License-Identifier: Apache-2.0
---
annotations:
  category: "Security"
  licenses: "Apache-2.0"
apiVersion: "v2"
dependencies:
  - name: "common"
    version: "^2.x.x"
    repository: "https://charts.bitnami.com/bitnami"
description: "A whiteboard widget for the Element messenger"
home: "https://github.com/nordeck/matrix-neoboard"
name: "matrix-neoboard-widget"
type: "application"
version: "0.2.0"
...
