name: Deploy to Neotoolsuite Staging

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Input the image tag to deploy'
        required: true

jobs:
  deploy-stage:
    name: Deploy to Neotoolsuite Stage
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Clone repo to get the helm charts
      - uses: actions/checkout@v4

      - name: Checkout valhalla for values
        uses: actions/checkout@v4
        with:
          ref: dev
          sparse-checkout: |
            /cluster/neotoolsuite-stage/neoboard/values-neotoolsuite-stage.yaml
          sparse-checkout-cone-mode: false
          repository: nordeck/valhalla
          token: ${{ secrets.PACKAGE_TOKEN }}
          path: valhalla
          persist-credentials: false

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Create Kubeconfig
        run: |
          # Extract the base64 encoded config data and write this to the KUBECONFIG
          echo "${{ secrets.KUBECONFIG_NEOTOOLSUITE_STAGE }}" | base64 -d > /tmp/config
          chmod 600 /tmp/config
          echo "KUBECONFIG=/tmp/config" >> $GITHUB_ENV

      - name: deploy k8s to cluster
        run: |
          helm upgrade --install neoboard ./charts/matrix-neoboard-widget -f ./valhalla/cluster/neotoolsuite-stage/neoboard/values-neotoolsuite-stage.yaml -n matrix -set image.tag=${{ github.event.inputs.image_tag }}

      - name: restart rollout
        run: |
          kubectl rollout restart deployment neoboard -n matrix
